FROM pvzd-client-env
MAINTAINER r2h2 <rhoerbe@hoerbe.at>


# install MOCCA (requires GUI)
RUN curl -O http://webstart.buergerkarte.at/mocca/webstart/mocca.jnlp

COPY opt/PVZDjava /opt/PVZDjava
COPY opt/PVZDpolman /opt/PVZDpolman
ENV JAVA_HOME=/etc/alternatives/java_sdk_1.8.0 \
    JDK_HOME=/etc/alternatives/java_sdk_1.8.0 \
    JRE_HOME=/etc/alternatives/java_sdk_1.8.0/jre
WORKDIR /opt/PVZDpolman/dependent_pkg
RUN cd pyjnius && python3.4 setup.py install && cd ..
RUN cd ordereddict-1.1 && python3.4 setup.py install
#RUN cd json2html && python3.4 setup.py install  && cd ..
RUN cd json2html && python3.4 setup.py install

RUN chmod +x /opt/PVZDpolman/PolicyManager/tests/testPMP.sh /opt/PVZDpolman/PolicyManager/tests/testPAtool.sh
WORKDIR /opt/PVZDpolman/PolicyManager
#COPY start.sh /start.sh
#RUN chmod a+x /start.sh
#CMD ["/start.sh"]

