FROM rhoerbe/pvzd-client-env
MAINTAINER r2h2 <rhoerbe@hoerbe.at>


# install MOCCA (requires GUI)
RUN curl -O http://webstart.buergerkarte.at/mocca/webstart/mocca.jnlp

ADD opt/PVZDpolman /opt/PVZDpolman
ADD opt/PVZDjava /opt/PVZDjava
WORKDIR /opt/PVZD/PolicyManager
RUN chmod +x /opt/PVZD/PolicyManager/tests/testPMP.sh /opt/PVZD/PolicyManager/tests/testPAtool.sh

#ADD start.sh /start.sh
#RUN chmod a+x /start.sh
#CMD ["/start.sh"]

# Clean up yum when done.
#RUN yum -y clean all

