FROM centos:centos7
MAINTAINER r2h2 <rhoerbe@hoerbe.at>

# -> https://github.com/CentOS/sig-cloud-instance-images/issues/22
ENV container docker
RUN yum -y swap -- remove systemd-container systemd-container-libs -- install systemd systemd-libs

RUN yum -y update
RUN yum -y groupinstall "Development Tools" --setopt=group_package_types=mandatory,default,optional
RUN yum -y groups install "GNOME Desktop"
RUN yum -y install java-1.8.0-openjdk-devel.x86_64
RUN yum -y install epel-release
RUN yum -y install python34-devel
RUN curl https://bootstrap.pypa.io/get-pip.py | python3.4
ENV pip=pip3.4

# do stuff from PVZD/PolicyManager/requirements.txt step by step
RUN yum -y install libffi-devel openssl-devel
RUN $pip install cffi pyOpenSSL

RUN $pip install cython future gitdb GitPython pytz requests simplejson

